//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluiTec.Vision.VisionHost.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContactText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactText() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluiTec.Vision.VisionHost.Resources.ContactText", typeof(ContactText).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About me ähnelt.
        /// </summary>
        internal static string AboutMeHeader {
            get {
                return ResourceManager.GetString("AboutMeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I am a hobby developer. A hobby developer, who has made a lot of effort to secure all collected data to the best of his knowledge. No more and no less. ähnelt.
        /// </summary>
        internal static string AboutMeText {
            get {
                return ResourceManager.GetString("AboutMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Address ähnelt.
        /// </summary>
        internal static string AddressHeader {
            get {
                return ResourceManager.GetString("AddressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact ähnelt.
        /// </summary>
        internal static string ContactHeader {
            get {
                return ResourceManager.GetString("ContactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright / Performance Protection ähnelt.
        /// </summary>
        internal static string CopyrightHeader {
            get {
                return ResourceManager.GetString("CopyrightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The content, works and information provided on this website are subject to German copyright law and the right to protection of services. Any kind of copying, processing, distribution, storage and any kind of exploitation outside the limits of copyright requires the prior written consent of the respective copyright owner. The unauthorized copying / saving of the provided information on these websites is not permitted and punishable. ähnelt.
        /// </summary>
        internal static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;a href=&quot;http://www.musterproject.net/disclaimer-muster&quot;&gt; Disclaimer-Source &lt;/a&gt; ähnelt.
        /// </summary>
        internal static string DataProtectionDisclaimerSource {
            get {
                return ResourceManager.GetString("DataProtectionDisclaimerSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Protection ähnelt.
        /// </summary>
        internal static string DataProtectionHeader {
            get {
                return ResourceManager.GetString("DataProtectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By visiting the Internet site, information (date, time, page accessed, IP address, UserAgent) is stored via access to the server. ähnelt.
        /// </summary>
        internal static string DataProtectionText1 {
            get {
                return ResourceManager.GetString("DataProtectionText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If personal data are collected, this is done, if possible, only with the prior consent of the user of the website. The transfer of the data to third parties does not take place without the express consent of the user. ähnelt.
        /// </summary>
        internal static string DataProtectionText2 {
            get {
                return ResourceManager.GetString("DataProtectionText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The provider points out that the transmission of data on the Internet has security gaps and a complete protection of the data before access by third parties can not be ensured. The provider accepts no liability for the damage caused by such security gaps. ähnelt.
        /// </summary>
        internal static string DataProtectionText3 {
            get {
                return ResourceManager.GetString("DataProtectionText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The use of contact data by third parties for commercial use is expressly rejected. Unless the provider has previously given his written consent. The provider reserves the right to take legal steps in the event of the unsolicited transmission of advertising information, eg spam mails. ähnelt.
        /// </summary>
        internal static string DataProtectionText4 {
            get {
                return ResourceManager.GetString("DataProtectionText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die External links ähnelt.
        /// </summary>
        internal static string ExternalLinksHeader {
            get {
                return ResourceManager.GetString("ExternalLinksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The website contains &quot;external links&quot; (links) to other websites, on the contents of which the provider of the website has no influence. For this reason, the provider can not assume any liability for these contents. The respective provider of the linked website is responsible for the content and correctness of the information provided. At the time of linking no infringements were recognizable. If you become aware of such an infringement, the link will be removed immediately. ähnelt.
        /// </summary>
        internal static string ExternalLinksText {
            get {
                return ResourceManager.GetString("ExternalLinksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imprint ähnelt.
        /// </summary>
        internal static string ImprintHeader {
            get {
                return ResourceManager.GetString("ImprintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limitation of liability ähnelt.
        /// </summary>
        internal static string LegalHeader {
            get {
                return ResourceManager.GetString("LegalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The content of the Internet site was created with the greatest possible care and conscience. However, the provider of this website does not assume any liability for the topicality, completeness and correctness of the pages and content provided. ähnelt.
        /// </summary>
        internal static string LegalText1 {
            get {
                return ResourceManager.GetString("LegalText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die As a service provider, the provider of this website is responsible for its own content and information provided on these pages according to the general laws in accordance with § 7 (1) TMG; According to §§ 8 to 10 TMG, however, is not obliged to monitor the transmitted or stored third-party information. The removal or blocking of these contents takes place immediately from the time of the knowledge of a concrete infringement. Liability is only possible from the time of obtaining the knowledge. ähnelt.
        /// </summary>
        internal static string LegalText2 {
            get {
                return ResourceManager.GetString("LegalText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account linking ähnelt.
        /// </summary>
        internal static string LinkingHeader {
            get {
                return ResourceManager.GetString("LinkingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This page allows you to link various user accounts. The &lt;a href=&quot;https://identityserver.io/&quot;&gt; IdentityServer &lt;/a&gt; is used for this. ähnelt.
        /// </summary>
        internal static string LinkingText1 {
            get {
                return ResourceManager.GetString("LinkingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In this connection, i.d.R. Information exchanged between this and other service providers. If ever information is shared - this is done exclusively with your own consent. ähnelt.
        /// </summary>
        internal static string LinkingText2 {
            get {
                return ResourceManager.GetString("LinkingText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy ähnelt.
        /// </summary>
        internal static string PrivacyHeader {
            get {
                return ResourceManager.GetString("PrivacyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Responsible as of MDStV ähnelt.
        /// </summary>
        internal static string ResponsibleText {
            get {
                return ResourceManager.GetString("ResponsibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Safety ähnelt.
        /// </summary>
        internal static string SafetyHeader {
            get {
                return ResourceManager.GetString("SafetyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The collected data is stored in a database of my choice. Your password is not stored in the plaintext - but in the form of a secure hash to avoid the compromising of other access data. ähnelt.
        /// </summary>
        internal static string SafetyText {
            get {
                return ResourceManager.GetString("SafetyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SSL ähnelt.
        /// </summary>
        internal static string SslHeader {
            get {
                return ResourceManager.GetString("SslHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I use a free SSL certificate from &lt;a href=&quot;https://letsencrypt.org/&quot;&gt; LetsEncrypt &lt;/a&gt;, which encrypts the communication between you and my server. ähnelt.
        /// </summary>
        internal static string SslText {
            get {
                return ResourceManager.GetString("SslText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terms of Use ähnelt.
        /// </summary>
        internal static string TermsOfUseHeader {
            get {
                return ResourceManager.GetString("TermsOfUseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usage data ähnelt.
        /// </summary>
        internal static string UsagedataHeader {
            get {
                return ResourceManager.GetString("UsagedataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optimizing this site ähnelt.
        /// </summary>
        internal static string UsagedataListEntry1 {
            get {
                return ResourceManager.GetString("UsagedataListEntry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detecting malicious users and bots ähnelt.
        /// </summary>
        internal static string UsagedataListEntry2 {
            get {
                return ResourceManager.GetString("UsagedataListEntry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registration is possible after registration. After such a registration, all activities of the user (as far as I can reasonably) are stored together with the personal data. (Log) ähnelt.
        /// </summary>
        internal static string UsagedataText {
            get {
                return ResourceManager.GetString("UsagedataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die These logs are: ähnelt.
        /// </summary>
        internal static string UsagedataText2 {
            get {
                return ResourceManager.GetString("UsagedataText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (And thus ultimately you and your protection) ähnelt.
        /// </summary>
        internal static string UsagedataText3 {
            get {
                return ResourceManager.GetString("UsagedataText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (I will never send e-mails for advertising purposes - e-mails will be used to legitimize and inform the user) ähnelt.
        /// </summary>
        internal static string UserDataAdText {
            get {
                return ResourceManager.GetString("UserDataAdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User data ähnelt.
        /// </summary>
        internal static string UserdataHeader {
            get {
                return ResourceManager.GetString("UserdataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authentication of the user ähnelt.
        /// </summary>
        internal static string UserdataListEntry1 {
            get {
                return ResourceManager.GetString("UserdataListEntry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact to the user by mail ähnelt.
        /// </summary>
        internal static string UserdataListEntry2 {
            get {
                return ResourceManager.GetString("UserdataListEntry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By registering, I collect various user data which I collect exclusively for the following purposes: ähnelt.
        /// </summary>
        internal static string UserdataText {
            get {
                return ResourceManager.GetString("UserdataText", resourceCulture);
            }
        }
    }
}
