//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluiTec.Vision.Server.Host.AspCoreHost.Resources.Views.Shared {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Functions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Functions() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluiTec.Vision.Server.Host.AspCoreHost.Resources.Views.Shared._Functions", typeof(_Functions).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alexa ähnelt.
        /// </summary>
        internal static string Function_Alexa {
            get {
                return ResourceManager.GetString("Function_Alexa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vision wurde zur Nutzung über Sprachdienste wie Alexa erstellt. ähnelt.
        /// </summary>
        internal static string Function_Alexa_Description {
            get {
                return ResourceManager.GetString("Function_Alexa_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Computersteuerung ähnelt.
        /// </summary>
        internal static string Function_ComputerControl {
            get {
                return ResourceManager.GetString("Function_ComputerControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kontrolliere deinen Computer - weit weg von Maus und Tastatur. ähnelt.
        /// </summary>
        internal static string Function_ComputerControl_Description {
            get {
                return ResourceManager.GetString("Function_ComputerControl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In Bälde ähnelt.
        /// </summary>
        internal static string Function_Future {
            get {
                return ResourceManager.GetString("Function_Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Funktionen sind bald auch über den Google Assistenten nutzbar. ähnelt.
        /// </summary>
        internal static string Function_Future_Description {
            get {
                return ResourceManager.GetString("Function_Future_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SmartHome ähnelt.
        /// </summary>
        internal static string Function_SmartHome {
            get {
                return ResourceManager.GetString("Function_SmartHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kontrolliere dein SmartHome - mit eigenen Befehlen. ähnelt.
        /// </summary>
        internal static string Function_SmartHome_Description {
            get {
                return ResourceManager.GetString("Function_SmartHome_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steam ähnelt.
        /// </summary>
        internal static string Function_Steam {
            get {
                return ResourceManager.GetString("Function_Steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du kannst Steam-Funktionen auslösen und so Spiele starten oder beenden. ähnelt.
        /// </summary>
        internal static string Function_Steam_Description {
            get {
                return ResourceManager.GetString("Function_Steam_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VLC Player ähnelt.
        /// </summary>
        internal static string Function_VLC {
            get {
                return ResourceManager.GetString("Function_VLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vision ermöglicht dir deinen VLC-Player per Sprache zu steuern. ähnelt.
        /// </summary>
        internal static string Function_VLC_Description {
            get {
                return ResourceManager.GetString("Function_VLC_Description", resourceCulture);
            }
        }
    }
}
