//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluiTec.Vision.AuthHost.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomeText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeText() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluiTec.Vision.AuthHost.Resources.HomeText", typeof(HomeText).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An amazon account ähnelt.
        /// </summary>
        internal static string AmazonAccount {
            get {
                return ResourceManager.GetString("AmazonAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Computer control ähnelt.
        /// </summary>
        internal static string ComputerControl {
            get {
                return ResourceManager.GetString("ComputerControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A computer with friday installed, thats running permanently ähnelt.
        /// </summary>
        internal static string ComputerWithFriday {
            get {
                return ResourceManager.GetString("ComputerWithFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A computer with jarvis installed ähnelt.
        /// </summary>
        internal static string ComputerWithJarvis {
            get {
                return ResourceManager.GetString("ComputerWithJarvis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        internal static string HomeHeader {
            get {
                return ResourceManager.GetString("HomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move window ähnelt.
        /// </summary>
        internal static string MoveWindow {
            get {
                return ResourceManager.GetString("MoveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start computer ähnelt.
        /// </summary>
        internal static string StartComputer {
            get {
                return ResourceManager.GetString("StartComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start process ähnelt.
        /// </summary>
        internal static string StartProcess {
            get {
                return ResourceManager.GetString("StartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shut down computer ähnelt.
        /// </summary>
        internal static string StopComputer {
            get {
                return ResourceManager.GetString("StopComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alexa, tell jarvis to move steam to screen 2 ähnelt.
        /// </summary>
        internal static string TellMoveWindow {
            get {
                return ResourceManager.GetString("TellMoveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alexa, start Jarvis ähnelt.
        /// </summary>
        internal static string TellStartComputer {
            get {
                return ResourceManager.GetString("TellStartComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alexa, tell jarvis to start steam ähnelt.
        /// </summary>
        internal static string TellStartProcess {
            get {
                return ResourceManager.GetString("TellStartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alexa, tell jarvis to shutdown ähnelt.
        /// </summary>
        internal static string TellStopComputer {
            get {
                return ResourceManager.GetString("TellStopComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alexa, tell jarvis to go faster / rewind ähnelt.
        /// </summary>
        internal static string TellVlcFastForwardRewind {
            get {
                return ResourceManager.GetString("TellVlcFastForwardRewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alexa, tell jarvis i want to watch films ähnelt.
        /// </summary>
        internal static string TellVlcFindFilms {
            get {
                return ResourceManager.GetString("TellVlcFindFilms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alexa, tell jarvis i want to watch series ähnelt.
        /// </summary>
        internal static string TellVlcFindSeries {
            get {
                return ResourceManager.GetString("TellVlcFindSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alexa, tell jarvis to go fullscreen ähnelt.
        /// </summary>
        internal static string TellVlcFullscreen {
            get {
                return ResourceManager.GetString("TellVlcFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alexa, tell jarvis to start playback ähnelt.
        /// </summary>
        internal static string TellVlcStart {
            get {
                return ResourceManager.GetString("TellVlcStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alexa, tell jarvis to stop playback ähnelt.
        /// </summary>
        internal static string TellVlcStop {
            get {
                return ResourceManager.GetString("TellVlcStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A vision account ähnelt.
        /// </summary>
        internal static string VisionAccount {
            get {
                return ResourceManager.GetString("VisionAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VLC control ähnelt.
        /// </summary>
        internal static string VlcControl {
            get {
                return ResourceManager.GetString("VlcControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fast forward and rewind ähnelt.
        /// </summary>
        internal static string VlcFastForwardRewind {
            get {
                return ResourceManager.GetString("VlcFastForwardRewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find films ähnelt.
        /// </summary>
        internal static string VlcFindFilms {
            get {
                return ResourceManager.GetString("VlcFindFilms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find series ähnelt.
        /// </summary>
        internal static string VlcFindSeries {
            get {
                return ResourceManager.GetString("VlcFindSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go fullscreen ähnelt.
        /// </summary>
        internal static string VlcFullscreen {
            get {
                return ResourceManager.GetString("VlcFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start playing ähnelt.
        /// </summary>
        internal static string VlcStart {
            get {
                return ResourceManager.GetString("VlcStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop playing ähnelt.
        /// </summary>
        internal static string VlcStop {
            get {
                return ResourceManager.GetString("VlcStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What you need? ähnelt.
        /// </summary>
        internal static string WhatDoYouNeed {
            get {
                return ResourceManager.GetString("WhatDoYouNeed", resourceCulture);
            }
        }
    }
}
