//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluiTec.Vision.Client.Windows.EndpointManager.Resources.Localization.Views.Setup.Wizard {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidateSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidateSettings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluiTec.Vision.Client.Windows.EndpointManager.Resources.Localization.Views.Setup." +
                            "Wizard.ValidateSettings", typeof(ValidateSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upnp-Konfigfuration hinzufügen ähnelt.
        /// </summary>
        public static string AddUpnpLabel {
            get {
                return ResourceManager.GetString("AddUpnpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konnektivität prüfen ähnelt.
        /// </summary>
        public static string CheckConnectivityLabel {
            get {
                return ResourceManager.GetString("CheckConnectivityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Webserver ist nicht erreichbar. ähnelt.
        /// </summary>
        public static string CheckConnectiviyErrorMessage {
            get {
                return ResourceManager.GetString("CheckConnectiviyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Webserver konnte nicht konfiguriert werden. ähnelt.
        /// </summary>
        public static string ConfigureHttpErrorMessage {
            get {
                return ResourceManager.GetString("ConfigureHttpErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Webserver konfigurieren ähnelt.
        /// </summary>
        public static string ConfigureHttpLabel {
            get {
                return ResourceManager.GetString("ConfigureHttpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Führt verschiedene Aufgaben zur Validierung der (neuen) Einstellungen aus. ähnelt.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aufgaben ausführen ähnelt.
        /// </summary>
        public static string ExecuteLabel {
            get {
                return ResourceManager.GetString("ExecuteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upnp-Konfiguration entfernen ähnelt.
        /// </summary>
        public static string RemoveUpnpLabel {
            get {
                return ResourceManager.GetString("RemoveUpnpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen speichern ähnelt.
        /// </summary>
        public static string SaveSettingsLabel {
            get {
                return ResourceManager.GetString("SaveSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Server konnte nicht gestartet werden. ähnelt.
        /// </summary>
        public static string StartServerErrorMessage {
            get {
                return ResourceManager.GetString("StartServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server starten ähnelt.
        /// </summary>
        public static string StartServerLabel {
            get {
                return ResourceManager.GetString("StartServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Server konnte nicht gestoppt werden. ähnelt.
        /// </summary>
        public static string StopServerErrorMessage {
            get {
                return ResourceManager.GetString("StopServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server stoppen ähnelt.
        /// </summary>
        public static string StopServerLabel {
            get {
                return ResourceManager.GetString("StopServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aufgaben: ähnelt.
        /// </summary>
        public static string TasksLabel {
            get {
                return ResourceManager.GetString("TasksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen überprüfen ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
